name: everfam
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.1.5 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  #code_generators
  freezed_annotation: ^2.4.1
  equatable: ^2.0.0

  #state_managment
  flutter_bloc: ^8.1.3
  bloc: ^8.1.2

  #calendar
  table_calendar: ^3.0.9

  #firebase
  firebase_analytics: ^10.6.3
  cloud_firestore: ^4.12.2
  firebase_auth: ^4.12.1
  firebase_core: ^2.21.0
  firebase_messaging: ^14.7.3
  firebase_remote_config: ^4.3.3

  cupertino_icons: ^1.0.2

  #json
  json_annotation: ^4.8.1

  #navigation
  auto_route: ^7.8.4

  #gap
  gap: ^3.0.1

  #dependencies_injection
  injectable: ^2.3.2
  get_it: ^7.6.4

dev_dependencies:
  flutter_test:
    sdk: flutter

  #code_generators
  freezed: ^2.4.5
  build_runner: ^2.4.6

  #linter
  very_good_analysis: ^5.1.0

  #json
  json_serializable: ^6.7.1

  #testing
  fake_cloud_firestore: ^2.4.3
  bloc_test: ^9.1.5
  mockito: ^5.4.2

  #dependencies_injection
  injectable_generator: ^2.4.1

flutter:
  uses-material-design: true

  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
